trigger:
- main
- develop
- feature/*
- bugfix/*

pool:
  vmImage: 'windows-latest'

variables:
  repository: 'walmartpayment'

stages:
- stage: 'Build'
  jobs:
  - job: 'DockerBuild'
    steps:
     - script: dotnet build --configuration $(buildConfiguration)
       displayName: 'dotnet build $(buildConfiguration)'

     - script: dotnet publish -f $(dotNetFramework) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
       displayName: Publish Project 

     - task: Npm@1
       displayName: 'Client Tests'
       inputs:
         command: 'custom'
         workingDir: 'ClientApp'
         customCommand: 'run test'