trigger:
- main
- develop
- feature/*
- bugfix/*

pool:
  vmImage: 'windows-latest'

variables:
  repository: 'walmartpayment'

stages:
- stage: 'Build'
  jobs:
  - job: 'DockerBuild'
    steps:
     - script: dotnet build --configuration $(buildConfiguration)
       displayName: 'dotnet build $(buildConfiguration)'

     

     - task: Npm@1
       displayName: 'Client Tests'
       inputs:
         command: 'custom'
         workingDir: 'ClientApp'
         customCommand: 'run test'
         customEndpoint: 
     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         
